### GET ALL GOALS
GET http://localhost:8080/users/goals/EHwDJwISVCPEG33lkQbXGIGJN1h1

### Create Goal
POST http://localhost:8080/users/goals/add HTTP/1.1
Content-Type: application/json

{
    "userId": "sampleUserId",
    "title": "Run 5K",
    "description": "I want to be able to run 5 kilometers without stopping by the end of the month.",
    "startDate": "2023-07-06T00:00:00.000Z",
    "targetDate": "2023-07-31T00:00:00.000Z",
    "progress": 0,
    "completed": false,
    "notes": "I'll start by running 1 kilometer and add half a kilometer every three days."
}

### Update Goal
PUT http://localhost:8080/users/goals/EHwDJwISVCPEG33lkQbXGIGJN1h1/gfXUv6Ga1TIsnksZa2UP HTTP/1.1
Content-Type: application/json

{
    "title": "Run 5K",
    "description": "I want to be able to run 5 kilometers without stopping by the end of the month.",
    "startDate": "2023-07-06T00:00:00.000Z",
    "targetDate": "2023-07-31T00:00:00.000Z",
    "progress": 0,
    "completed": true,
    "notes": "I'll start by running 1 kilometer and add half a kilometer every three days."
}

### Delete goal
DELETE http://localhost:8080/users/goals/EHwDJwISVCPEG33lkQbXGIGJN1h1/u6ys77js5T5zy559W1Wt
