### Get all users
Get http://localhost:8080/users

### Get by userId
Get http://localhost:8080/users/EHwDJwISVCPEG33lkQbXGIGJN1h1
### Add User
POST http://localhost:8080/users/add HTTP/1.1
Content-Type: application/json

{
    "firstName": "LeRoy",
    "lastName": "Jenkins",
    "email": "leroy@gmail.com",
    "password": "leroy123"
}



